### ISSUE TITLE
spotify podcasts not embeded

### ISSUE THREAD

**Issue by AuryPolaris** [Vap0r1ze/vpc-spotimbed#10] opened 2022-09-13 15:25 UTC
a friend of mine sent this podcast link and it doesn't embed with Spotimbed
spotify:https://open.spotify.com/show/07YmR3znx7imqdYyIB0ByI?si=61932ea8835045e4

**Comment by Vap0r1ze** [comment] 2022-09-13 16:21
Duplicate of #2, but since you opened this I will try to work on it right now

**Closed as completed by Vap0r1ze** 2022-09-13 16:21 UTC
